apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: knu-chat-namespace
spec:
  selector:
    app: log
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30172
  type: NodePort
